plugins { id 'com.android.application' }
android {
 namespace 'com.psa.hotspothelper'
 compileSdk 35
 defaultConfig { applicationId 'com.psa.hotspothelper'; minSdk 28; targetSdk 28; versionCode 3; versionName '0.2' }
 compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}

dependencies { testImplementation 'junit:junit:4.13.2' }
